# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mostly Harmless
tagline:          'Blag'
description:      'Data Analyst at <a href="http://viki.com" target="_blank">Viki</a>. Caffeine-powered, music-loving, tree-hugger. Tweet to me <a href="https://twitter.com/stuti90" target="_blank">@stuti90</a>.'
url:              http://lanyon.getpoole.com
baseurl:          'stuti90.github.io/'
paginate:         5

author:
  name:           'Stuti'
  url:            https://twitter.com/stuti90

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon